local ServerScriptService = game:GetService("ServerScriptService")
local HungerService = require(ServerScriptService.HungerService)
local FoodService = require(ServerScriptService.FoodService)
local MutationService = require(ServerScriptService.MutationService)
local MutationController = require(ServerScriptService.MutationController)
local LavaZoneService = require(ServerScriptService.LavaZoneService)
local ZoneService = require(ServerScriptService.ZoneService)
local CombatService = require(ServerScriptService.CombatService)
local DebugMonitorService = require(ServerScriptService.DebugMonitorService)

-- Initialize Game Services
print("Initializing Game Services...")
DebugMonitorService.Init()
ZoneService.Init()
HungerService.Init()
FoodService.Init()
MutationService.Init()
LavaZoneService.Init()
CombatService.Init()
MutationController.Init()
print("Game Services Initialized!")
